runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  secure: always
  redirect_http_response_code: 301
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  secure: always
  redirect_http_response_code: 301
  static_files: www/\1
  upload: www/(.*)
